code: seeds_card_ng_config
guiCode: >-
  <#assign wp=JspTaglibs[ "/aps-core"]>

  <script async src="<@wp.resourceURL
  />widgets/seeds-card-ng/js/main-es2015.js"></script>

  <@wp.currentWidget param="config" configParam="cardname" var="configName" />

  <ng-seedscard-details cardname="${configName}"/>
