code: seeds_card_ng_config
titles:
  en: Seeds Card NG
  it: Seeds Card NG
group: free
configUi:
  customElement: seeds-card-config
  resources:
    - widgets/seeds-card-config/static/js/runtime.js
    - widgets/seeds-card-config/static/js/vendor.js
    - widgets/seeds-card-config/static/js/main.js
